palmetto/palmetto-components

src/components/CheckboxInput/CheckboxInput.jsx
src/components/CheckboxInput/CheckboxInput.scss
src/components/CheckboxInput/CheckboxInput.stories.jsx
src/components/FormLabel/FormLabel.scss
src/styles/reset.scss

- Adds error state for CheckboxInput
- Uses the `<FormLabel/>` component for the CheckboxInput label instead of custom div. 
- adds `isRequired` prop to CheckboxInput

feat (CheckboxInput): error and isRequired props

---

package.json
src/components/Button/Button.scss
src/components/colors/Colors.stories.jsx

@juanfabrega for next release.

refactor (Button): use tokens instead of hardcoded values

---

package.json
src/components/Button/Button.scss
src/components/FormLabel/FormLabel.jsx
yarn.lock

release v0.1.4

---

package.json
src/components/Button/Button.jsx
src/components/Button/Button.stories.jsx
src/components/CheckboxInput/CheckboxInput.jsx
src/components/CheckboxInput/CheckboxInput.stories.jsx
src/components/Formik/Formik.stories.jsx
src/components/Formik/FormikCheckboxInput/FormikCheckboxInput.jsx
src/components/Formik/FormikTextInput/FormikTextInput.jsx
src/components/InputValidationMessage/InputValidationMessage.stories.jsx
src/components/TextInput/TextInput.stories.jsx
src/components/colors/Colors.stories.jsx
yarn.lock

Added storybook-state so that we could render our standard components without complicated stateful wrappers. This also has a major benefit of having the source code in our docs actually look like our components, so devs can reference the source in order to understand how to use the components vs the previously obfuscated source.

Storybook improvements

---

src/components/CheckboxInput/CheckboxInput.jsx
src/components/CheckboxInput/CheckboxInput.test.jsx

adds some basic tests for CheckboxInput component

test (CheckboxInput): add tests

---

jest.setup.js
src/components/Button/Button.test.jsx
src/components/CheckboxInput/CheckboxInput.test.jsx
src/components/FormLabel/FormLabel.test.jsx
src/components/Heading/Heading.test.jsx
src/components/SelectInput/SelectInput.test.jsx
src/components/TextInput/TextInput.test.jsx
src/setupTests.js

Fixes https://github.com/palmetto/palmetto-components/issues/87
testConfig.js was an obsolete file that I used out of habit from using CRA. Added global dependencies to correct file.

Test Config

---

src/components/Button/Button.jsx
src/components/CheckboxInput/CheckboxInput.jsx
src/components/FormLabel/FormLabel.jsx
src/components/Formik/FormikCheckboxInput/FormikCheckboxInput.jsx
src/components/Formik/FormikSelectInput/FormikSelectInput.jsx
src/components/Formik/FormikTextInput/FormikTextInput.jsx
src/components/Heading/Heading.jsx
src/components/InputValidationMessage/InputValidationMessage.jsx
src/components/SelectInput/SelectInput.jsx
src/components/TextInput/TextInput.jsx

Move Props to Top

---

src/components/FormLabel/FormLabel.module.scss

fix (FormLabel): prevent external spacing styles from cascading

---

webpack.config.js

Modify hash to include className.

---

package.json
src/components/Table/TableHead/TableHead.tsx

Bumping the package to version 0.3.0

bumping package version to 0.3.0

---

src/docs/BorderRadius.stories.mdx
src/docs/Breakpoints.stories.mdx
src/docs/FontSize.stories.mdx
src/docs/Spacing.stories.mdx

docs: add prop value column to tokens

---

.releaserc
docs/CONTRIBUTING.md
package.json
yarn.lock

Adds angular default convention which includes the following by default:
* build: Changes that affect the build system or external dependencies (example scopes: gulp, broccoli, npm)
* ci: Changes to our CI configuration files and scripts (example scopes: Circle, BrowserStack, SauceLabs)
* docs: Documentation only changes
* feat: A new feature
* fix: A bug fix
* perf: A code change that improves performance
* refactor: A code change that neither fixes a bug nor adds a feature
* test: Adding missing tests or correcting existing tests

Commit types

---

.github/workflows/deploy-to-github-pages.yml
.github/workflows/publish-to-chromatic.yml
.github/workflows/pull-request.yml
.github/workflows/semantic-release.yml
.releaserc
README.md
docs/CONTRIBUTING.md

NOTE: Once this is merged we will need to move the target branch to `main`. The main branch is currently up to date with this one. We can then delete `master` branch.

change master branch to main in relevant places

---

src/components/Button/Button.module.scss
src/components/Button/Button.stories.mdx
src/components/Button/Button.test.jsx
src/components/Button/Button.tsx
src/styles/variables/buttons.scss

This PR adds color variations as well as a boolean prop to render outlined versions of the buttons.

Button variations

---

src/components/Alert/Alert.stories.mdx
src/components/Alert/Alert.test.tsx
src/components/Alert/Alert.tsx
src/components/Button/Button.tsx
src/components/Heading/Heading.stories.mdx
src/components/Heading/Heading.test.tsx
src/components/Heading/Heading.tsx
src/components/Spinner/Spinner.stories.mdx
src/components/Spinner/Spinner.tsx

Refactor all color variations for components to use the `variant` prop.

Variant refactor

---

src/components/TextLink/TextLink.stories.mdx

docs(TextLink): accepts html anchor attributes

---

src/components/Formik/Formik.stories.mdx
src/components/Formik/FormikTextareaInput/FormikTextareaInput.test.tsx
src/components/Formik/FormikTextareaInput/FormikTextareaInput.tsx
src/components/index.ts

formik binding for textarea input.

Text area formik

---

src/components/Table/TableHeaderCell/TableHeaderCell.module.scss
src/styles/variables/table.scss

Increases the default table cell padding so that it aligns with other component's (such as Card) default padding. Also increases the difference between the default table and a compact table.

fix(Table): increase cell padding

---

package.json
src/components/Alert/Alert.module.scss
src/components/Box/Box.stories.mdx
src/components/Box/Box.tsx
src/components/Button/Button.module.scss
src/components/FormLabel/FormLabel.module.scss
src/components/RadioGroup/RadioGroup.module.scss
src/docs/FontWeight.stories.mdx
src/lib/tokens.ts
src/styles/variables/buttons.scss
src/styles/variables/forms.scss
src/types/index.ts
yarn.lock

1. Adds `fontWeight` prop to Box
2. Documents `font-weight` tokens

Font Weight

---

package.json
src/components/TextLink/TextLink.stories.mdx
src/components/TextLink/TextLink.test.tsx
src/components/TextLink/TextLink.tsx

Re-structure TextLink component for different ergonomics with React Router.

Text link props

---

.storybook/main.js
src/components/Box/Box.stories.mdx
src/components/Formik/Formik.stories.mdx
src/components/Formik/FormikTimePicker/FormikTimePicker.test.tsx
src/components/Formik/FormikTimePicker/FormikTimePicker.tsx
src/components/SelectInput/SelectInput.stories.mdx
src/components/SelectInput/SelectInput.tsx
src/components/TimePicker/TimePicker.stories.mdx
src/components/TimePicker/TimePicker.test.tsx
src/components/TimePicker/TimePicker.tsx
src/components/index.ts

TimePicker component. Based on the SelectInput, but generates times based on start/end and interval.

Time picker

---

src/components/Box/Box.test.jsx
src/components/Popover/Popover.test.tsx
src/styles/display.scss
src/types/index.ts

also removes a leftover `debug()` in a test

add display grid option to Box

---

src/styles/reset.scss

https://chanind.github.io/javascript/2019/09/28/avoid-100vh-on-mobile-web.html

fix: Adjust Reset Rules

---

src/components/RadioGroup/RadioGroup.module.scss
src/components/RadioGroup/RadioGroup.stories.mdx
src/components/RadioGroup/RadioGroup.tsx
src/components/RadioGroup/RadioInput/RadioInput.module.scss
src/components/RadioGroup/RadioInput/RadioInput.tsx

feat(RadioGroup): allow for horizontally aligned radio button inputs

---

.stylelintrc
package.json
yarn.lock

pin storybook 6.1 and update all packages before 1.0 release

chore(deps): Update packages

---

index.d.ts
package.json
src/components/Icon/Icon.stories.mdx
src/components/Icon/Icon.test.tsx
src/components/Icon/Icon.tsx
src/lib/tokens.ts
yarn.lock

auto-documents new icons from palmetto-design-tokens

feat: Icon Set

---

package.json
yarn.lock

included with updated palmetto-design-tokens package

feat: box, pin-add icons

---

src/components/DatePicker/DatePicker.stories.mdx

docs: initiate DatePicker stories in the past so that chromatic diff isn't triggered every time

---

src/components/Button/Button.stories.mdx
src/components/Button/Button.stories.tsx

moves some of the more complex stories to a "For Chromatic" folder so that the documentation isn't so overwhelming. Makes the code samples much simpler and easier to digest.

docs(Button): separate Button doc examples from visual regression stories

---

package.json
yarn.lock

Adds social media icons to Icon component
result preview:

chore(deps): adds social media icons from palmetto-design-tokens

---

package.json
yarn.lock

adds `question-mark` and `info` icons

chore(deps): palmetto design tokens 0.29.0

---

package.json
src/components/Modal/Modal.module.scss
src/components/Popover/Popover.module.scss
src/components/Table/TableBody/TableBodyCell/TableBodyCell.module.scss
src/styles/variables/modal.scss
yarn.lock

sizes `2xs` through `2xl` box-shadow tokens

feat: add and document box-shadow tokens

---

src/components/Box/Box.stories.mdx

Addresses: https://github.com/palmetto/palmetto-components/issues/388

Correct Docs for Box's Radius Prop

---

package.json
src/components/Box/Box.Overview.stories.mdx
src/components/Box/Box.Playground.stories.tsx
src/components/Box/Box.VisualTests.stories.tsx
src/components/Box/Box.tsx
src/lib/getDimensionCss.test.js
src/lib/getDimensionCss.ts
src/types/index.ts
yarn.lock

- adds responsive `minHeight` and `maxHeight` props to `<Box />` component
- adds visual regression tests for minHeight and maxHeight
- unit tests

feat(Box): add responsive minHeight and maxHeight props

---

src/components/Heading/Heading.Overview.stories.mdx
src/components/Heading/Heading.Playground.stories.tsx
src/components/Heading/Heading.VisualTests.stories.tsx
src/components/Heading/Heading.tsx

docs: Heading component documentation re-organization

---

src/components/CheckboxInput/CheckboxInput.Overview.stories.mdx
src/components/CheckboxInput/CheckboxInput.Playground.stories.tsx
src/components/DateInput/DateInput.Overview.stories.mdx
src/components/FileUpload/FileUpload.Overview.stories.mdx
src/components/FileUpload/FileUpload.Playground.stories.tsx
src/components/FormLabel/FormLabel.Overview.stories.mdx
src/components/FormLabel/FormLabel.Playground.stories.tsx
src/components/FormLabel/FormLabel.stories.mdx
src/components/RadioGroup/RadioGroup.Overview.stories.mdx
src/components/RadioGroup/RadioGroup.Playground.stories.tsx
src/components/SelectInput/SelectInput.Overview.stories.mdx
src/components/SelectInput/SelectInput.Playground.stories.tsx
src/components/TextInput/TextInput.Overview.stories.mdx
src/components/TextInput/TextInput.Playground.stories.tsx
src/components/TextInput/TextInput.VisualTests.stories.tsx
src/components/TextareaInput/TextareaInput.Overview.stories.mdx
src/components/TextareaInput/TextareaInput.Playground.stories.tsx
src/components/TimePicker/TimePicker.Overview.stories.mdx
src/components/TimePicker/TimePicker.Playground.stories.tsx

Moves form input components to follow new documentation structure
```
Component
-- Overview
-- Playground
-- Visual Tests (if applicable)
```

Component Documentation Reorganization

---

src/components/Card/Card.tsx
src/components/Card/components/CardFooter/CardFooter.tsx
src/components/Card/components/CardHeader/CardHeader.tsx
src/components/Card/components/CardSection/CardSection.tsx

This PR addresses: https://github.com/palmetto/palmetto-components/issues/411

Card spread props

---

.storybook/preview.js
src/components/Button/Button.Overview.stories.mdx
src/components/Button/Button.test.jsx
src/components/Button/Button.tsx
src/components/FileUpload/FileUpload.tsx
src/components/Spinner/Spinner.tsx

https://github.com/palmetto/palmetto-components/issues/400

fix(Button): proper navigation when using react-router Link

---

.storybook/preview.js
src/components/Button/Button.Overview.stories.mdx
src/components/Button/Button.tsx
src/components/TextLink/TextLink.test.tsx
src/components/TextLink/TextLink.tsx
src/lib/reactRouterClickHandler.ts

This PR addresses: https://github.com/palmetto/palmetto-components/issues/406

fix(TextLink): React router text link

---

.github/pull_request_template.md
src/components/DatePicker/DatePicker.stories.mdx

This PR addresses: https://trello.com/c/x3UwaGBr/525-create-a-pr-template-with-a-checklist-of-items-to-test-before-considering-a-merge

docs(PR): pr template

---

src/components/TextInput/TextInput.tsx

This PR addresses this issue:  https://github.com/palmetto/palmetto-components/issues/420
(No UI changes done)

fix(TextInput): accept all input types as props

---

package.json
yarn.lock

Add solid and outlined circle caret icons

chore(deps): palmetto-design-tokens 0.36.0

---

src/components/Modal/components/ModalBody/ModalBody.tsx

This PR addresses this issue: https://trello.com/c/Nk9J926L/553-modal-dynamic-height-issue

fix(Modal): preventing positioning issue with overflowing dynamic height content

---

src/components/Box/Box.Overview.stories.mdx

This PR addresses this issue: The box story for the border color hover state is not working properly.

fix box hover story

---

src/components/index.ts

fix(SelectInputNative): added proper export for formik component

---

src/components/TextareaInput/TextareaInput.module.scss
src/components/TextareaInput/TextareaInput.tsx

fix(TextareaInput): fixing error styles for text-area-input

---

src/components/Formik/FormikSelectInputNative/FormikSelectInputNative.test.jsx
src/components/SelectInputNative/SelectInputNative.test.tsx
src/components/SelectInputNative/SelectInputNative.tsx

fix(SelectInputNative): fixing value prop type for select native

---

src/components/SelectInputNative/SelectInputNative.module.scss

select input native pointer events

---

src/components/SelectInput/SelectInput.module.scss

refactor(SelectInput): important label margin

---

src/components/ResponsiveProvider/ResponsiveProvider.tsx
src/hooks/useBreakpoint/useBreakpoint.Overview.stories.mdx

conditional window object for ssr

---

src/components/ResponsiveProvider/ResponsiveProvider.tsx
src/hooks/useBreakpoint/useBreakpoint.Overview.stories.mdx

Responsive provider ssr

---

src/components/ResponsiveProvider/ResponsiveProvider.tsx

fix(ResponsiveProvider): optional chain window

---

.github/workflows/pull-request.yml
package.json
src/components/Box/Box.Overview.stories.mdx
src/components/Box/Box.VisualTests.stories.tsx
src/docs/colors/Colors.stories.jsx
yarn.lock

feat(TransparentColor): Updating tokens to include transparent color for background/border.

---

.github/workflows/publish-to-chromatic.yml
src/components/Modal/Modal.module.scss

Fix deployment pipeline failures due to mismatch in node version.

ci(Chromatic): Node version

---

.github/workflows/publish-to-chromatic.yml
src/components/Modal/Modal.module.scss

ci(Chromatic): Chromatic node version

---

src/components/Modal/Modal.module.scss
src/components/TabsSlider/TabsSlider.tsx

fix(TabsSlider): allow changing of Tabs slider element via 'as' prop.

---

.releaserc
docs/CONTRIBUTING.md

Beta releases

---

.github/workflows/semantic-release.yml

ci(betaSemantincRelease): add beta branch to semantic release action

---

src/components/Modal/Modal.Overview.stories.mdx
src/components/Modal/Modal.VisualTests.stories.jsx
src/components/Modal/Modal.tsx

feat(Modal): Modal max width

---

src/components/Box/Box.Overview.stories.mdx
src/components/Box/Box.Playground.stories.tsx
src/components/Box/Box.VisualTests.stories.tsx
src/components/Box/Box.tsx
src/styles/flex.scss

This PR addresses this issue: https://github.com/palmetto/palmetto-components/issues/483

fix(Box): flex direction reverse classes

---

package.json

fix(Publish): Prepublish not using correct script.

---

src/components/Modal/Modal.tsx

fix(Modal): remove requirement of maxWidth on modal

---

package.json
src/components/DateInput/DateInput.test.tsx
src/components/DateInput/DateInput.tsx
src/components/Modal/Modal.tsx
src/components/TextInput/TextInput.tsx
yarn.lock

This PR addresses this issue: https://github.com/palmetto/palmetto-components/issues/495

fix(DateInput): Date input with no label throws exception

---

src/components/Tabs/TabItem.tsx
src/components/Tabs/Tabs.test.tsx
src/components/Tabs/Tabs.tsx
src/components/TabsSlider/TabItem.tsx
src/components/TabsSlider/TabsSlider.test.tsx
src/components/TabsSlider/TabsSlider.tsx

fix(Tabs): change tab elements for clearer aria roles

---

src/components/Formik/FormikTextInput/FormikTextInput.jsx

Fixes a type error in the console:
Updated the types to match the documentation in storybook:

Updating Formik allowed types to match underlying TextInput

---

src/lib/cssShorthandToClasses.ts

This PR addresses this issue: https://github.com/palmetto/palmetto-components/issues/476

Box shorthand trim

---

package.json
yarn.lock

feat(tokens): Tokens update

---

package.json
src/components/Box/Box.Overview.stories.mdx
src/components/Box/Box.Playground.stories.tsx
src/components/Box/Box.VisualTests.stories.tsx
src/components/Box/Box.tsx
src/components/Button/Button.tsx
src/components/DateInput/DateInput.test.tsx
src/components/DateInput/DateInput.tsx
src/components/Formik/FormikSelectInputNative/FormikSelectInputNative.jsx
src/components/Formik/FormikTextInput/FormikTextInput.jsx
src/components/Modal/Modal.tsx
src/components/SelectInputNative/SelectInputNative.tsx
src/components/Tabs/TabItem.tsx
src/components/Tabs/Tabs.test.tsx
src/components/Tabs/Tabs.tsx
src/components/TabsSlider/TabItem.tsx
src/components/TabsSlider/TabsSlider.test.tsx
src/components/TabsSlider/TabsSlider.tsx
src/components/TextInput/TextInput.tsx
src/lib/cssShorthandToClasses.ts
src/styles/flex.scss
yarn.lock

chore: update beta with latest changes from main

---

package.json
src/components/Box/Box.Overview.stories.mdx
src/components/Box/Box.Playground.stories.tsx
src/components/Box/Box.VisualTests.stories.tsx
src/components/Box/Box.tsx
src/declarations.d.ts
src/docs/FontFamily.stories.mdx
src/lib/tokens.ts
src/types/index.ts
yarn.lock

feat(TokensAndBox): add font family option to box

---

src/components/Button/Button.module.scss

fix(Button): Disabled button pointer style

---

package.json
yarn.lock

Adds following icons:
- move
- download

chore(deps): palmetto-design-tokens 0.44.5

---

src/components/Accordion/Accordion.Overview.stories.mdx
src/components/Accordion/Accordion.test.tsx
src/components/Accordion/AccordionPanelSummary.tsx
src/components/Details/Details.test.tsx
src/components/Details/DetailsSummary.tsx
src/components/FileUpload/FileUpload.module.scss
src/components/FileUpload/FileUpload.test.tsx
src/components/FileUpload/FileUpload.tsx
src/components/TextInput/TextInputSizeUtilities.ts

This PR addresses this issue: https://trello.com/c/N4ZLXGhC/722-onclick-on-root-element-of-fileupload-component

File input props

---

package.json
yarn.lock

add icons cloud-forecast, cloud-rain, cloud-sun, sun, trend-up

---

src/components/Toggle/Toggle.Playground.stories.tsx

This PR addresses this issue:  https://trello.com/c/YnNZGQgx/477-re-organize-component-documentation

docs(Toggle): add Playground story

---

src/components/Toggle/Toggle.test.jsx
src/components/Toggle/Toggle.tsx

test(Toggle): size tests

---

src/components/Formik/FormikCheckboxInput/FormikCheckboxInput.test.jsx
src/components/Formik/FormikCheckboxInput/FormikCheckboxInput.tsx
src/components/Formik/FormikRadioGroup/FormikRadioGroup.test.jsx
src/components/Formik/FormikRadioGroup/FormikRadioGroup.tsx
src/components/Formik/FormikSelectInput/FormikSelectInput.test.jsx
src/components/Formik/FormikSelectInput/FormikSelectInput.tsx
src/components/Formik/FormikSelectInputNative/FormikSelectInputNative.test.jsx
src/components/Formik/FormikSelectInputNative/FormikSelectInputNative.tsx
src/components/Formik/FormikTextInput/FormikTextInput.test.jsx
src/components/Formik/FormikTextInput/FormikTextInput.tsx
src/components/Formik/FormikTextareaInput/FormikTextareaInput.test.tsx
src/components/Formik/FormikTextareaInput/FormikTextareaInput.tsx
src/components/Formik/FormikTimePicker/FormikTimePicker.test.tsx
src/components/Formik/FormikTimePicker/FormikTimePicker.tsx
src/components/Formik/FormikTimePickerNative/FormikTimePickerNative.test.tsx
src/components/Formik/FormikTimePickerNative/FormikTimePickerNative.tsx
src/components/Formik/FormikToggle/FormikToggle.test.jsx
src/components/Formik/FormikToggle/FormikToggle.tsx

This PR addresses this issue: https://github.com/palmetto/palmetto-components/issues/542

Add handling of nested object validation errors for Formik inputs

---

package.json
yarn.lock

chore(deps): palmetto-design-tokens 0.49.1

---

tsconfig.json

This PR addresses this issue: Due to the compilation step including TS types, and an assertion being compiled down to JS (generating an error with a type), I have now excluded internal library types from the compilation process

build(TS): correct exclude statements

---

src/components/TextInput/TextInput.module.scss
src/components/Toggle/Toggle.Overview.stories.mdx
src/components/Toggle/Toggle.VisualTests.stories.tsx
src/components/Toggle/Toggle.module.scss
src/components/Toggle/Toggle.test.jsx
src/components/Toggle/Toggle.tsx

This PR addresses this issue: https://github.com/palmetto/palmetto-components/issues/437
Adding responsive sizes to Toggle component

Toggle responsive size

---

package.json

This PR addresses this issue: https://github.com/palmetto/palmetto-components/issues/567

fix(deps): add uuid as dependency

---

.github/workflows/code-scan.yml

Adds CodeQL scanning to the repository which is available for free on public repos.
https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/about-code-scanning

ci(code-scan): Add CodeQL for GitHub Security

---

src/components/TabsSlider/TabsSlider.VisualTests.stories.tsx

This PR addresses this issue: https://github.com/palmetto/palmetto-components/issues/570

fix(TabsSlider): fixing visual tests for tabsslider

---

src/components/Toast/Toast.VisualTests.stories.tsx

This PR addresses this issue: https://github.com/palmetto/palmetto-components/issues/575

fix(chromatic): shortening delay for toast visual tests

---

src/components/Box/Box.tsx
src/components/Table/Table.Overview.stories.mdx
src/components/Table/TableBody/TableBody.module.scss
src/components/Table/TableBody/TableBodyCell/TableBodyCell.module.scss
src/components/Table/TableBody/TableBodyCell/TableBodyCell.test.tsx
src/components/Table/TableBody/TableBodyCell/TableBodyCell.tsx
src/components/Table/TableHead/TableHeaderCell/TableHeaderCell.module.scss
src/components/Table/TableHead/TableHeaderCell/TableHeaderCell.tsx
src/components/Table/constants.ts
src/components/TabsSlider/TabsSlider.tsx
src/styles/display.scss
src/types/index.ts
yarn.lock

This PR addresses this issue: https://github.com/palmetto/palmetto-components/issues/592

fix(Table): table refactor to improve custom styling.

---

src/components/OptionTile/OptionTile.tsx

This PR addresses this issue: https://github.com/palmetto/palmetto-components/issues/595

fix(OptionTile): issue with childGap on option tile

---

src/components/CheckboxInput/CheckboxInput.Overview.stories.mdx
src/components/CheckboxInput/CheckboxInput.Playground.stories.tsx
src/components/CheckboxInput/CheckboxInput.VisualTests.stories.tsx
src/components/CheckboxInput/CheckboxInput.test.jsx
src/components/CheckboxInput/components/Checkbox.Overview.stories.tsx
src/components/CheckboxInput/components/Checkbox.module.scss
src/components/CheckboxInput/components/Checkbox.test.tsx
src/components/CheckboxInput/components/Checkbox.tsx
src/components/CheckboxInput/components/CheckboxIcon.tsx

This PR addresses this issue: https://github.com/palmetto/palmetto-components/issues/437

feat(Checkbox): responsive checkbox sizes

---

package.json
src/components/CheckboxInput/CheckboxInput.Overview.stories.mdx
src/components/CheckboxInput/CheckboxInput.Playground.stories.tsx
src/components/CheckboxInput/CheckboxInput.VisualTests.stories.tsx
src/components/CheckboxInput/CheckboxInput.tsx
src/components/CheckboxInput/components/Checkbox.test.tsx
src/components/CheckboxInput/components/Checkbox.tsx
src/components/CheckboxInput/components/CheckboxIcon.tsx
yarn.lock

This PR addresses this issue: https://github.com/palmetto/palmetto-components/issues/599

feat(Checkbox): Indeterminate checkbox

---

package.json
src/components/FormLabel/FormLabel.Playground.stories.tsx
src/components/FormLabel/FormLabel.module.scss
src/components/FormLabel/FormLabel.tsx
src/components/Formik/FormikRadioGroup/FormikRadioGroup.tsx
src/components/OptionTile/OptionTile.tsx
src/components/RadioGroup/RadioGroup.Overview.stories.mdx
src/components/RadioGroup/RadioGroup.Playground.stories.tsx
src/components/RadioGroup/RadioGroup.VisualTests.stories.tsx
src/components/RadioGroup/RadioGroup.tsx
src/components/RadioGroup/RadioInput/RadioInput.module.scss
src/components/RadioGroup/RadioInput/RadioInput.tsx
src/components/RadioGroup/RadioInput/RadioInputIcon.tsx
src/components/Toggle/Toggle.tsx
yarn.lock

This PR addresses this issue: https://github.com/palmetto/palmetto-components/issues/437

Responsive radio

---

src/hooks/useBreakpoint/useBreakpoint.ts

This PR addresses this issue: N/A

fix function to use correct breakpoint start

---

src/lib/createComponent/createComponent.Overview.stories.mdx
src/lib/createComponent/createComponent.test.tsx
src/lib/createComponent/createComponent.tsx
src/lib/createComponent/index.ts
src/lib/index.ts

This PR addresses this issue: https://github.com/palmetto/palmetto-components/issues/577

feat(utilities): Create component

---

.github/workflows/pull-request.yml
.github/workflows/semantic-release.yml
package.json
yarn.lock

This PR addresses this issue: N/A

feat(storybook): storybook to 6.3

---

.github/workflows/pull-request.yml

- [] DOCS: All new component work is covered in that component's `Overview` docs.

fix(ci): specify node version in all jobs

---

src/components/Table/Table.Overview.stories.mdx
src/types/index.ts

This PR addresses this issue: [#647](https://github.com/palmetto/palmetto-components/issues/647)
- [n/a] DOCS: All new component work is covered in a component `Playground`.
- [n/a] DOCS: All new visual changes or options are covered under relevant components' `VisualTests`.
- [n/a] I have commented my code, particularly in hard-to-understand areas
- [n/a] I have added tests that prove my fix is effective or that my feature works

feat(Table): Support ReactNode as Column heading

---

src/components/FileUpload/FileUpload.tsx

This PR addresses this issue: https://github.com/palmetto/palmetto-components/issues/651

fix(FileUpload): File upload click propagation

---

src/components/CheckboxInput/components/Checkbox.test.tsx
src/components/CheckboxInput/components/CheckboxIcon.tsx
src/components/FileUpload/FileUpload.tsx
src/components/OptionTile/OptionTile.tsx
src/components/RadioGroup/RadioGroup.tsx
src/components/RadioGroup/RadioInput/RadioInputIcon.tsx
src/components/Toggle/Toggle.module.scss

This PR addresses this issue: https://trello.com/c/7iKJyD8Q/715-update-radiogroup-and-optiontile-to-use-icon

fix(OptionTile): Option tile icons

---

package.json
yarn.lock

fix(deps): update chromatic cli to 6.0.5

---

package.json

feat(tokens): new icon in design-tokens

---

src/components/FileUpload/FileUpload.Overview.stories.mdx
src/components/FileUpload/FileUpload.test.tsx
src/components/FileUpload/FileUpload.tsx
yarn.lock

fix(FileUpload): Add case to storybook where there is no text for the FileUpload button

---

package.json
yarn.lock

chore(deps): palmetto-design-tokens 0.58.0

---

src/components/RadioGroup/RadioGroup.VisualTests.stories.tsx
src/components/RadioGroup/RadioGroup.tsx
src/components/RadioGroup/RadioInput/RadioInput.module.scss
src/components/RadioGroup/RadioInput/RadioInput.tsx

This PR addresses this issue: https://github.com/palmetto/palmetto-components/issues/662

fix(RadioInput): don't apply width and height to all label children

---

.stylelintrc
package.json
src/components/Button/Button.tsx
src/components/Card/Card.tsx
src/components/CategoryFilter/CategoryFilter.tsx
src/components/FormLabel/FormLabel.tsx
src/components/RadioGroup/RadioGroup.tsx
src/components/SelectInput/SelectInput.tsx
src/components/SelectInputNative/SelectInputNative.tsx
src/components/TextInput/TextInput.tsx
src/components/TextareaInput/TextareaInput.tsx
src/components/Toggle/Toggle.tsx
src/styles/variables/buttons.scss
src/styles/variables/card.scss
src/styles/variables/forms.scss
yarn.lock

This PR addresses this issue: Component variables originally where set on the `:root` selector, which made it hard to theme using core token variables. This PR scoped them to specific class selectors which are then applied to the components that need the variables specifically.

feat(theming ): Scoped component variables

---

package.json
yarn.lock

This PR addresses this issue: Updating to latest palmetto-design-tokens release

feat(tokens): update tokens package

---

package.json

feat(tokens): updated icons

---

src/components/Button/Button.Overview.stories.mdx
src/components/Button/Button.VisualTests.stories.tsx
src/components/Button/Button.module.scss
src/components/Button/Button.test.jsx
src/components/Button/Button.tsx
src/components/FileUpload/FileUpload.test.tsx
src/components/Pagination/Pagination.test.tsx

This PR addresses this issue: Added ability to make button responsive.

feat(Button): responsive button

---

package.json

chore(deps): palmetto-design-tokens 0.60.4

---

package.json
src/docs/BorderRadius.stories.mdx
src/docs/colors/Colors.stories.jsx
yarn.lock

Updating beta branch to produce a release

fix: update with expanded border radius options

---

package.json
yarn.lock

feat: new greens

---

src/components/TextLink/TextLink.Overview.stories.mdx
src/components/TextLink/TextLink.module.scss
src/styles/variables/index.scss
src/styles/variables/links.scss

Adds theme tokens for TextLink component
This PR addresses this issue: https://trello.com/c/0BYfsU0F/1147-update-components-for-themability

feat(TextLink): theme tokens

---

src/components/CategoryFilter/CategoryFilter.Overview.stories.mdx
src/components/CategoryFilter/CategoryFilter.module.scss
src/components/CategoryFilter/CategoryFilter.tsx

This PR addresses this issue: https://trello.com/c/0BYfsU0F/1147-update-components-for-themability

feat(CategoryFilter): theme tokens

---

src/components/Badge/Badge.Overview.stories.mdx
src/components/Badge/Badge.Playground.stories.tsx
src/components/Badge/Badge.VisualTests.stories.tsx
src/components/Badge/Badge.constants.ts
src/components/Badge/Badge.module.scss
src/components/Badge/Badge.test.tsx
src/components/Badge/Badge.tsx

Refactors Badge component to allow for token theming
This PR addresses this issue: https://trello.com/c/0BYfsU0F/1147-update-components-for-themability

feat(Badge): theme tokens and responsive sizing

---

src/components/ResponsiveProvider/ResponsiveProvider.Codesandbox.stories.mdx
src/components/ResponsiveProvider/ResponsiveProvider.Overview.stories.mdx
src/components/ThemeProvider/ThemeProvider.Codesandbox.stories.mdx
src/components/ThemeProvider/ThemeProvider.Overview.stories.mdx

docs: move ThemeProvider and ResponsiveProvider to Providers category folder

---

package.json
src/components/Modal/Modal.stories.tsx
src/components/Modal/Modal.tsx
yarn.lock

This PR addresses this issue: Modal cannot be rendered in custom portal. NOTE: this change has us moving to a **FORKED** version of **reach-ui**. We will monitor progress on the reach-ui PR that was opened for this feature to confirm when we can move back to the official version. The change is currently necessary due to scoped theming needs from various teams.

feat(Modal): Render Modal in custom portal target.

---

.storybook/preview.js
src/components/Button/Button.module.scss
src/components/CategoryFilter/CategoryFilter.Overview.stories.mdx
src/components/CategoryFilter/CategoryFilter.module.scss
src/components/CategoryFilter/CategoryFilter.tsx
src/components/Pagination/Pagination.tsx
src/components/Tabs/Tabs.Overview.stories.mdx
src/components/Tabs/Tabs.module.scss
src/components/TabsSlider/TabsSlider.Overview.stories.mdx
src/components/TabsSlider/TabsSlider.module.scss
src/docs/Theming.stories.mdx

Adds theming example. I've added a few form inputs (TextInput, SelectInputNative, OptionTileGroup) but there themability is being addressed in a separate [pull request](https://github.com/palmetto/palmetto-components/pull/682)
https://user-images.githubusercontent.com/1447339/154564771-b4cf31ec-2605-460d-98f7-871b9ab4d2cc.mov

Theming Documentation

---

src/components/Toast/Toast.Overview.stories.mdx
src/components/Toast/Toast.test.tsx
src/components/Toast/ToastNotification.module.scss
src/components/Toast/ToastNotification.tsx

This PR addresses this issue: https://trello.com/c/OC9hgghM/1157-component-tokens
- Reduces the border radius and padding to make the Toast more visually distinct from Buttons.
- Adds and document component design tokens for theming a Toast component
```
'--toast-notification-background-color': '--color-brand-grey-800',
'--toast-notification-font-color': '--color-brand-white-500',
'--toast-notification-border-radius': '--size-border-radius-sm',
'--toast-notification-box-shadow': '--size-box-shadow-2xs',
'--toast-notification-dismiss-border-color': '--color-brand-grey-600',
'--toast-notification-dismiss-color': '--color-brand-white-500',
```

feat(Toast): theme tokens

---

src/components/Card/Card.Overview.stories.mdx
src/components/Card/Card.module.scss
src/components/Card/Card.test.jsx
src/components/Card/Card.tsx
src/components/Card/components/CardFooter/CardFooter.test.jsx
src/components/Card/components/CardFooter/CardFooter.tsx
src/styles/variables/card.scss
src/styles/variables/index.scss

This PR addresses this issue: https://trello.com/c/OC9hgghM/1157-component-tokens
Adds component design tokens to the Card component for theming.
```
'--card-background-color': '--color-brand-white-500',
'--card-border-radius': '--size-border-radius-md',
'--card-box-shadow': '--size-box-shadow-sm',
'--card-section-border-color': '--color-brand-grey-100',
'--card-footer-background-color': '--color-brand-grey-50',
```

feat(Card): theme tokens

---

package.json
src/components/Button/Button.Playground.stories.tsx
src/components/Button/Button.VisualTests.stories.tsx
src/components/Button/Button.tsx
src/components/Heading/Heading.tsx
src/components/Popover/Popover.VisualTests.stories.tsx
yarn.lock

test(Button): add focus state visual tests

---

src/components/FileUpload/FileUpload.VisualTests.stories.tsx
src/components/FileUpload/FileUpload.tsx

fixes #377
This PR addresses this issue: #377  

fix(FileUpload): make helpText block level item for mobile

---

src/components/Button/Button.Overview.stories.mdx
src/components/Button/Button.VisualTests.stories.tsx
src/components/Button/Button.module.scss

This PR addresses this issue: #703 
Vertically centers button contents so that the label and icons are consistently aligned.

fix(Button): vertically center button contents

---

package.json
yarn.lock

chored(deps): palmetto-design-tokens 0.61.2

---

package.json
yarn.lock

chore(deps): palmetto-design-tokens 0.61.0-beta.5

---

docs/CONTRIBUTING.md

feat: force a beta release

---

package.json
src/components/Toggle/Toggle.Overview.stories.mdx
src/components/Toggle/Toggle.module.scss
yarn.lock

This PR addresses this issue: https://trello.com/c/1MWtfgzG/1176-publish-updated-color-palette

feat(Colors): updated brand colors

---

package.json
yarn.lock

This PR addresses this issue: https://trello.com/c/uzAlkGKd/1167-copy-document-icon
copy-document icon before
after

fix(Icon): copy-document icon

---

src/components/Modal/Modal.tsx

docs: spelling

---

src/components/MediaModal/MediaModal.Overview.stories.mdx

feat(MediaModal): fix warning in documentation

---

.storybook/preview.js
src/docs/Foundation.DesignPrincples.stories.mdx
src/docs/Foundation.DesignTokens.stories.mdx

This PR addresses this issue: https://trello.com/c/dbc72OXu/1181-document-design-principles
- Creates a "Foundation" category in the storybook documentation nav.
- Moves design tokens to the foundation category
- Adds Design Principles documentation page

docs: create Foundation category, and document ux design principles

---

src/components/Button/Button.tsx
src/components/OptionTile/OptionTile.Overview.stories.mdx
src/components/OptionTile/OptionTile.module.scss

https://github.com/palmetto/palmetto-components/issues/738
Adding theme tokens to the `OptionTile`. This component uses global form control variables for theming, however if it is necessary to have this one component diverge from these global form styles, this change adds unique variables. The flow of theming for this will now be `component token --> custom global form control token --> fallback (form control defaults)`

feat: [738] option tile theme tokens

---

package.json
yarn.lock

adds a `camera` icon to the Icon component

feat(Icon): adds "camera" icon

---

src/components/Table/Table.Overview.stories.mdx
src/components/Table/TableBody/TableBodyCell/TableBodyCell.module.scss

This PR addresses this issue: Table theming of table cells was not working properly. Also added example story to have a chromatic test in the future.

fix: improve table theming

---

package.json

feat: updated design tokens

---

src/components/Toggle/Toggle.Overview.stories.mdx
src/components/Toggle/Toggle.module.scss

This PR addresses this issue: https://trello.com/c/MJXflPw6/1240-identify-update-components-that-need-changes-based-on-new-color-palette
Darken error state red to match other form inputs
| before | after|
| --- | --- |
| ![Screen Shot 2022-04-14 at 3 41 25 PM](https://user-images.githubusercontent.com/1447339/163489442-d3333d23-f356-4c4e-bed2-6d00805e2170.png) | ![Screen Shot 2022-04-14 at 3 42 15 PM](https://user-images.githubusercontent.com/1447339/163489465-7debd6ee-8af5-4fcf-817b-54b6245951a5.png) |

fix(Toggle): darken toggle error background color to 500

---

src/components/Alert/Alert.Overview.stories.mdx
src/components/Alert/Alert.module.scss

This PR addresses this issue: https://trello.com/c/MJXflPw6/1240-identify-update-components-that-need-changes-based-on-new-color-palette
Add a `300` color border to Alerts.
Preview build: https://5ed9214b642dc10022b50a2d-hzgdjbuqbq.chromatic.com/?path=/docs/components-alert-overview--default-story
| before | after|
| --- | --- |
| ![Screen Shot 2022-04-14 at 4 06 10 PM](https://user-images.githubusercontent.com/1447339/163491374-48c6070c-1863-49fb-813c-a3857f7d595f.png) | ![Screen Shot 2022-04-14 at 4 06 38 PM](https://user-images.githubusercontent.com/1447339/163491413-aba344c2-cf1b-4a98-bfdb-c384590fea14.png) | 

fix(Alert): add 300 color border

---

src/components/MediaModal/MediaModal.module.scss
src/components/MediaModal/MediaModal.tsx

This PR addresses this issue: #727 
Diff

fix(MediaModal): style focus state for close button

---

src/components/Duration/Duration.Codesandbox.stories.mdx
src/components/Duration/Duration.Overview.stories.mdx
src/components/Duration/Duration.test.jsx
src/components/Duration/Duration.tsx
src/components/Duration/Durations.Playground.stories.tsx
yarn.lock

feat: add Duration component

---

src/components/Duration/Duration.tsx
src/components/index.ts

fix: two bugs in Duration Component

---

.github/workflows/semantic-release.yml
src/components/TextInput/TextInput.Overview.stories.mdx
src/components/TextInput/TextInput.VisualTests.stories.tsx
src/components/TextInput/TextInput.module.scss

This PR addresses this issue: https://trello.com/c/a7kL8qvX/1271-textinput-focus-state-styling
Current
After
Also moves doc stories to visual tests instead to shorten the docs page.

fix(TextInput): focus states visual stories

---

src/components/RadioGroup/RadioGroup.VisualTests.stories.tsx
src/components/RadioGroup/RadioInput/RadioInput.module.scss
src/components/RadioGroup/RadioInput/RadioInput.tsx

This PR addresses this issue: #779 

fix(RadioGroup): add visual focus state

---

src/components/TextInput/TextInput.module.scss
src/docs/FormTheming.stories.mdx

fix(TextInput): visual focus state

---

.github/workflows/semantic-release.yml

Reverts https://github.com/palmetto/palmetto-components/pull/790

build: stop publishing to github packages

---

package.json
yarn.lock

chore(deps): palmetto-design-tokens 0.65.0

---

src/components/Accordion/AccordionPanelSummary.tsx

fix(Accordion): allow setting of vertical alignment with caret

---

src/components/FileUpload/FileUpload.Overview.stories.mdx
src/components/FileUpload/FileUpload.Playground.stories.tsx
src/components/FileUpload/FileUpload.tsx

Adds `isOutlined` and a `white` variant to teh FileUpload button.

feat(FileUpload): add white and outline variants

---

src/components/FileUpload/FileUpload.Overview.stories.mdx
src/components/FileUpload/FileUpload.Playground.stories.tsx
src/components/FileUpload/FileUpload.test.tsx
src/components/FileUpload/FileUpload.tsx

Allows the icon in the FileUpload button to be customized to any in our icon library.

feat(FileUpload): allow icon to be customized

---

package.json
src/components/Formik/FormikSelectInput/FormikSelectInput.test.jsx
src/components/Formik/FormikTimePicker/FormikTimePicker.test.tsx
src/components/SelectInput/SelectInput.test.jsx
yarn.lock

chore: react-select 3.1.0 to 4.3.1

---

package.json
yarn.lock

chore(deps): remove file-loader dependency

---

yarn.lock

build(deps): popperjs, react-popper, classnames, date-fns

---

yarn.lock

build(deps): babel package updates

---

.storybook/main.js
package.json
yarn.lock

Build/storybook 6.5.15

---

package.json
yarn.lock

https://palmetto.atlassian.net/browse/UX-279?atlOrigin=eyJpIjoiYjI5MWY1ODViMmExNDE3Nzg0NTg5MzVlNThiM2RlNDEiLCJwIjoiaiJ9

feat(Icons): antenna, wifi, wifi-off

---

yarn.lock

build(deps): bump chromatic 6.0.5 to 6.17.4

---

yarn.lock

build(deps): @storybook/addon-essentials@6.5.16, @storybook/addons@6.5.16, @storybook/react@6.5.16

---

package.json
src/components/Box/Box.Overview.stories.mdx
yarn.lock

Adds medium 500 font weight token

build(deps): bump palmetto-design-tokens from 0.67.0 to 0.68.0

---

package.json

No github issue nor Trello card. Just enabling turbo snap for Chromatic

use turbosnap

---

package.json
yarn.lock

build(deps): palmetto-design-tokens 0.68.0 to 0.69.1

---

src/components/RadioGroup/RadioInput/RadioInputIcon.tsx
src/docs/FormTheming.stories.mdx
src/styles/variables/forms.scss

fix(RadioGroup): remove unused token

---

package.json
yarn.lock

feat(Icon): skip, rewind

---

src/components/CategoryFilter/CategoryFilter.Overview.stories.mdx
src/components/CategoryFilter/CategoryFilter.module.scss
src/components/CategoryFilter/CategoryFilter.tsx

Adds font color tokens to the CategoryFilter component to support theming 

feat(CategoryFilter): add font color tokens

---

package.json
yarn.lock

feat(Icon): arrows-maximize

---

src/components/CategoryFilter/CategoryFilter.Overview.stories.mdx
src/components/CheckboxInput/components/Checkbox.module.scss
src/components/CheckboxInput/components/Checkbox.test.tsx
src/components/CheckboxInput/components/Checkbox.tsx
src/components/CheckboxInput/components/CheckboxIcon.tsx
src/components/Modal/Modal.Overview.stories.mdx
src/components/Modal/components/ModalFooter/ModalFooter.tsx
src/components/Modal/components/ModalHeader/ModalHeader.test.jsx
src/components/Modal/components/ModalHeader/ModalHeader.tsx
src/components/OptionTile/OptionTile.tsx
src/components/Tabs/TabItem.tsx
src/components/Toggle/Toggle.Overview.stories.mdx
src/components/Toggle/Toggle.module.scss
src/docs/FormTheming.stories.mdx

Adds design-tokens (css vars) for CheckboxInput, Modal, Toggle and Tabs. 

feat: CheckboxInput, Modal, Toggle, Tabs design tokens and documentation

---

package.json
yarn.lock

feat(tokens): 6xl width

---

src/components/Alert/Alert.VisualTests.stories.tsx
src/components/CategoryFilter/CategoryFilter.VisualTests.stories.tsx
src/components/CategoryFilter/CategoryFilter.constants.ts
src/components/OptionTile/OptionTile.VisualTests.stories.tsx

Reduce the number of stories (39 less) for chromatic snapshot testing. 
Components: 
- Alert
- CategoryFilter
- OptionTile

test: consolidate visual regression test stories

---

.github/workflows/code-scan.yml

update CodeQL actions to latest version

ci: CodeQL actions from v1 to v2

---

src/components/MediaModal/MediaModal.module.scss

Fixes stylelint warning on build step.

fix: stylelint warning

---

.github/workflows/pull-request.yml
package.json

Use chromatic turbosnap
https://www.chromatic.com/docs/turbosnap#configure

ci: use chromatic turbosnap

---

package.json
yarn.lock

With this change there will be font sizes
```
...
xl: 24
1xl: 32
2xl: 36
...
```
We will update naming convention in a subsequent breaking change

feat: 1xl font size

---

package.json
yarn.lock

This PR addresses this issue: https://palmetto.atlassian.net/browse/UX-491

feat(Icon): bank, cheque, laptop-computer

---

package.json
yarn.lock

https://palmetto.atlassian.net/browse/UX-504
adds icons: 
- solar-panels
- electric vehicle
- heat pump
- window

feat(Icons): solar-panels, electric vehicle, heat pump, window

---

src/components/Pagination/Pagination.Playground.stories.tsx

docs(Pagination): add more controls to playground

---

package.json
yarn.lock

build(deps): bump palmetto-design-tokens from 0.77.0 to 0.77.1

---

.storybook/main.js
package.json
yarn.lock

build(deps): remove redudant storybook add-ons

---

.github/workflows/pull-request.yml
.github/workflows/semantic-release.yml

ci: update from node 14 to 16

---

package.json
yarn.lock

build(deps): bump palmetto-design-tokens from 0.77.1 to 0.78.0

---

src/components/Button/Button.module.scss

fix(Button): secondary neutral hover color

---

src/components/Button/Button.VisualTests.stories.tsx
src/components/Button/Button.tsx
src/components/MediaModal/MediaModal.VisualTests.stories.tsx

fix(Button): loading state icon color

---

src/components/Button/Button.Overview.stories.mdx

docs(Button): tone documentation

---

src/components/FormControl/FormControl.tsx
src/stories/FormControls.stories.mdx

fix(FormControls): specify width 100 instead of relying on flex auto

---

src/components/TextInput/TextInput.tsx
src/components/TextInputFloating/TextInputFloating.module.scss
src/components/TextInputFloating/TextInputFloating.tsx

fix(TextInputFloating): prefix/suffix focus styles, clear icon

---

package.json
src/components/FileUpload/FileUpload.Overview.stories.mdx
src/components/FileUpload/FileUpload.tsx
src/components/FormControl/FormControl.tsx
src/components/FormLabel/FormLabel.module.scss
src/components/FormLabel/FormLabel.tsx
src/components/HelpText/HelpText.module.scss
src/components/HelpText/HelpText.tsx
src/components/SelectInputNativeFloating/SelectInputNativeFloating.Overview.stories.mdx
src/components/SelectInputNativeFloating/SelectInputNativeFloating.Playground.stories.tsx
src/components/SelectInputNativeFloating/SelectInputNativeFloating.module.scss
src/components/SelectInputNativeFloating/SelectInputNativeFloating.test.tsx
src/components/SelectInputNativeFloating/SelectInputNativeFloating.tsx
src/components/TextInputFloating/TextInputFloating.Overview.stories.mdx
src/components/TextInputFloating/TextInputFloating.test.tsx
src/components/TextInputFloating/TextInputFloating.tsx
src/components/Toggle/Toggle.tsx
src/components/index.ts
src/docs/FormTheming.stories.mdx
src/stories/FormControls.stories.mdx
src/styles/variables/forms.scss
yarn.lock

This PR addresses this issue: https://palmetto.atlassian.net/browse/UX-627

feat(SelectInputNativeFloating): new component

---

src/components/TextareaInputFloating/TextareaInputFloating.Overview.stories.mdx
src/components/TextareaInputFloating/TextareaInputFloating.Playground.stories.tsx
src/components/TextareaInputFloating/TextareaInputFloating.VisualTest.stories.tsx
src/components/TextareaInputFloating/TextareaInputFloating.module.scss
src/components/TextareaInputFloating/TextareaInputFloating.test.tsx
src/components/TextareaInputFloating/TextareaInputFloating.tsx
src/docs/FormTheming.stories.mdx

This PR addresses this issue: https://palmetto.atlassian.net/browse/UX-630?atlOrigin=eyJpIjoiZWUxZDRmNjVhMTBiNDI4YWFmNWZmMDQ3NjcxMGM4NWIiLCJwIjoiaiJ9

feat(TextareaInputFloating): new component

---

src/stories/FormControls.VisualTests.stories.tsx
src/stories/FormControls.stories.mdx

docs: floating and default input examples

---

package.json
yarn.lock

chore(deps): bump palmetto-design-tokens from 0.78.0 to 0.78.1

---

src/components/FormLabel/FormLabel.module.scss
src/components/SelectInput/SelectInput.module.scss
src/components/SelectInput/SelectInput.test.jsx
src/components/SelectInput/SelectInput.tsx
src/components/SelectInputNative/SelectInputNative.module.scss
src/components/SelectInputNativeInset/SelectInputNativeInset.module.scss

feat(SelectInputs): make dropdown indicator match icon

---

package.json
src/components/MediaModal/MediaModal.Overview.stories.mdx
src/components/MediaModal/MediaModal.VisualTests.stories.tsx
yarn.lock

Updates dropshadow styling via new palmetto-design-tokens package

feat: update drop shadows 

---

package.json
yarn.lock

feat: update drop shadows

---

yarn.lock

build: package updates

---

src/components/Button/Button.test.jsx
src/components/Button/Button.tsx

test(Button): loading state spinner variant tests

---

src/components/Modal/Modal.Overview.stories.mdx
src/components/Modal/Modal.VisualTests.stories.jsx
src/components/Modal/Modal.module.scss
src/components/Modal/Modal.test.tsx
src/components/Modal/components/ModalFooter/ModalFooter.tsx
src/components/Modal/components/ModalHeader/ModalHeader.tsx

feat: Modal dark mode

---

src/components/Table/Table.module.scss

fix(Table): dark mode loading state

---

src/components/Table/Table.Overview.stories.mdx
src/components/Table/Table.tsx
src/components/Table/TableBody/TableBody.module.scss
src/components/Table/TableBody/TableBody.tsx
src/components/Table/TableHead/TableHead.tsx
src/hooks/index.ts
src/hooks/useExpandableRow/useExpandableRow.test.tsx
src/hooks/useExpandableRow/useExpandableRow.ts

https://github.com/user-attachments/assets/4e7ed4a7-26ca-4c05-9f8b-c6e81cf3a674

feat(Table): Support for expandable rows

---

package.json
yarn.lock

The design token has been updated to the latest version to enable the use of new icons.

feat: update design token

---

package.json
yarn.lock

The palmetto-design-tokens has been updated to the latest version to enable the use of updated icons

feat: update token package

---

package.json
src/components/SelectInput/SelectInput.module.scss
src/components/SelectInput/SelectInput.test.jsx
src/components/SelectInput/SelectInput.tsx
src/types/index.ts
yarn.lock

This PR addresses this issue:  [https://palmetto.atlassian.net/browse/FIN-2928](https://palmetto.atlassian.net/browse/FIN-2928)
With the necessary upgrade to `react-select` the need for `@types/react-select` has been removed and typescript is native. However, with that...some types have been removed that were explicitly used here. To keep everything backwards compatible...those types have been recreated.
Before: 
After:

update react select styles when using portal

---

src/components/SelectInput/SelectInput.tsx

fix: bump version

---

src/components/SelectInput/SelectInput.tsx
src/types/index.ts

Update types from previous react-select update
A few `any` types are required because there is not a replacement with v5
https://react-select.com/upgrade#from-v4-to-v5

fix: update types
