- package.json
- src/components/CheckboxInput/CheckboxInput.scss
- src/components/index.js
palmetto-tokens needs to be added as a direct dependency of palmetto-components so that consumers don't have to install it explicitly.
This PR also adds the CheckboxInput to our index, hence exporting it for consumers.
> adding tokens as dev dependency

- src/components/TextInput/TextInput.jsx
- src/components/TextInput/TextInput.scss
- src/components/TextInput/TextInput.stories.jsx
Right now the grey colors are too blue, but waiting until Figma workflow is done to adjust. Also applies the "not-allowed" mouse cursor on hover so it's more obvious that a disabled input is disabled.
> feat (TextInput): not-allowed mouse cursor and color improvements to disabled input

- .github/workflows/pull-request.yml
- src/components/index.js
This makes it so that the following are run when a pull request is opened, synchronized, or reopened.
1. lint
2. unit tests
3. visual regression tests
Once this is merged, I want to make these checks required before merging is allowed.
> ci: Run lint, unit tests and chromatic on pull requests

- .babelrc
- package.json
- src/components/TextInput/TextInput.jsx
- src/components/TextInput/TextInput.stories.jsx
- src/components/TextInput/TextInput.test.jsx
- yarn.lock
NOTE: the babel plugins are to allow async/await usage with jest tests. not used currently but it will be useful when testing events with `userEvent`
> feat: adding maxlength prop on TextINput

- src/components/CheckboxInput/CheckboxInput.jsx
- src/components/CheckboxInput/CheckboxInput.stories.jsx
- src/components/CheckboxInput/CheckboxInput.test.jsx
- src/components/Formik/FormikCheckboxInput/FormikCheckboxInput.jsx
The `CheckboxInput` component now passes a full synthetic event back to library consumers when onChange fires. Corresponding tests, stories, and Formik binding have been changed accordingly.
> chore: refactor checkbox input API and corresponding components

- src/components/Button/Button.jsx
- src/components/CheckboxInput/CheckboxInput.jsx
- src/components/SelectInput/SelectInput.jsx
- src/components/TextInput/TextInput.jsx
fixes empty class properties appearing in the dom: 
currently
> fix: prevent empty class properties appearing in the dom

- src/components/Button/Button.test.jsx
adding this test in case the button markup gets refactored and we forget to assign the html button type.
> test (Button): add tests for button type

- package.json
- yarn.lock
https://github.com/advisories/GHSA-5q88-cjfq-g2mh
> security: bump codecov from 3.7.0 to 3.7.1

- .storybook/manager.js
- .storybook/palmettoTheme.js
- .storybook/preview.js
- package.json
- yarn.lock
Came across theming in the docs and just had to give it a go; swapped in Palmetto's logo for starters, then switched the theme to "dark" just to see what it would look like. Figure we can at least go with the logo change for now, just so the setup is committed to the repo for future use.
https://storybook.js.org/docs/configurations/theming/
> Setup Theming

- src/components/CheckboxInput/CheckboxInput.module.scss
- src/components/CheckboxInput/CheckboxInput.stories.mdx
- src/components/CheckboxInput/CheckboxInput.test.jsx
- src/components/CheckboxInput/CheckboxInput.tsx
- src/components/FormLabel/FormLabel.module.scss
- src/components/FormLabel/FormLabel.stories.mdx
- src/components/FormLabel/FormLabel.test.jsx
- src/components/FormLabel/FormLabel.tsx
- src/components/RadioGroup/RadioInput/RadioInput.tsx
- src/components/SelectInput/SelectInput.tsx
- src/components/TextInput/TextInput.jsx
- src/components/TextInput/TextInput.stories.mdx
Refactored label component (and corresponding components that depend on it) to take children, rather than a `labelText' prop. The label prop on our inputs is still required to be a string for accessibility reasons.
> Form label refactor

- src/docs/Height.stories.mdx
- src/docs/Width.stories.mdx
- src/lib/tokens.ts
Adds documentation of width and height tokens
> feat: width and height tokens

- package.json
- src/components/Box/Box.stories.mdx
- src/components/Box/Box.tsx
- src/docs/Height.stories.mdx
- src/docs/Width.stories.mdx
- src/lib/getDimensionCss.test.js
- src/lib/getDimensionCss.ts
- src/lib/types.ts
- yarn.lock
behaves the same as existing `width` and `height` props, except sets max width and height for the box.
> feat(Box): add max width and height props

- src/components/Button/Button.module.scss
- src/components/Button/Button.stories.mdx
- src/components/Button/Button.test.jsx
- src/components/Button/Button.tsx
This PR adds a version of the button that renders an anchor tag, when passed an href attribute. Useful for when we want page links that need to look like buttons.
> button-style anchor

- src/components/SelectInput/SelectInput.tsx
- src/components/TextInput/TextInput.stories.mdx
- src/components/TextInput/TextInput.tsx
When rendering adjacent TextInputs, the TextInputs should take up 100% of the available width.
For example
```
<Box row="column" childGap="lg">
<TextInput />
<TextInput />
</Box>
```
Currently looks like this
This PR does this:
> fix: make SelectInput and TextInput take up 100% parent width

- src/components/CheckboxInput/CheckboxInput.module.scss
- src/components/CheckboxInput/CheckboxInput.stories.mdx
- src/components/CheckboxInput/CheckboxInput.test.jsx
- src/components/CheckboxInput/CheckboxInput.tsx
- src/components/FormLabel/FormLabel.module.scss
- src/components/FormLabel/FormLabel.test.jsx
- src/components/FormLabel/FormLabel.tsx
- src/components/SelectInput/SelectInput.stories.mdx
- src/components/SelectInput/SelectInput.tsx
- src/components/TextInput/TextInput.stories.mdx
- src/components/TextInput/TextInput.tsx
- src/components/TextareaInput/TextareaInput.stories.mdx
- src/components/TextareaInput/TextareaInput.tsx
- src/styles/variables/forms.scss
Allows user to set helpful text that gets placed below the form's label.
TextInput
SelectInput
CheckboxInput
TextareaInput
> feat: Add help text to form inputs

- .github/workflows/pull-request.yml
This removes the PR jobs from being run after merging to master. Also adds build job to run on PRs so that we are sure the build is running before firing a release.
> removing pr jobs on pushes

- src/components/Box/Box.tsx
Ensuring that a string is an acceptable type for border width since it takes CSS shorthand.
> expand border width prop type

- src/components/Box/Box.tsx
We are accidentally calling `generateResponsiveClasses('flex-direction', direction),` which adds the `flex-direction-column` or `flex-direction-row` class twice to the element. This removes 1 of the calls so only 1 class name is added.
> fix(Box): prevent flex direction classes from being added twice

- .storybook/preview.js
- README.md
- src/docs/Contributing.stories.mdx
- src/docs/GetStarted.stories.mdx
- src/docs/Intro.stories.mdx
- Adds some basic pages for 
- Introduction
- Get Started
- Contributing
- Sets the order of the items in the storybook left nav
> docs: add introduction, get started, and contributing pages to storybook

- src/components/Box/Box.stories.mdx
For each "responsive" story, this pr adds a chromatic parameter to capture snapshots at different viewport widths. Because of the way storybook puts stories into an iframe, i had to add 20px to each of our breakpoint values. They end up being: 
- 320 - iphone 5
- 700 (680) - tablet
- 1012 (992) - desktop
- 1300 (1280) - hd
> test: adds breakpoints snapshots to capture responsive Box stories in Chromatic

- src/components/Box/Box.tsx
this avoids putting `flex-direction-column` on every single `Box` regardless if it's actually `display: flex`.
> fix(Box): include flex-direction class only on display flex

- src/lib/cssShorthandToClasses.test.ts
- src/lib/cssShorthandToClasses.ts
We have utility classes that set margin and padding values to 0, but we don't use them currently because the `cssShorthandToClasses` function only returns classnames if a value is not equal to zero or a border width. 
This prevents us from setting a spacing value to 0 at different breakpoints (see linked issue)
This change always returns a css classname if the spacing value is valid.
> fix: if a user specifies '0' as a spacing value, return the corresponding css className

- src/components/Modal/Modal.module.scss
before on tablet, the modal looks too narrow and unbalanced:
this pr increases the width on tablets so that content appears more balanced:
> fix(Modal): increase width to 70% of viewport on tablets

- src/styles/reset.scss
Because of our reset.scss, using an order list `ol` element renders a bullet list instead of numbered list. 
This change fixes that by removing the `list-style-type` property, and relying on the browser default to set the list type.
> fix: dont reset ol, ul list types because browser default is ok

- src/components/Alert/Alert.tsx
- src/components/Badge/Badge.tsx
- src/components/Button/Button.tsx
- src/components/Card/Card.tsx
- src/components/CheckboxInput/CheckboxInput.tsx
- src/components/DateInput/DateInput.tsx
- src/components/FileUpload/FileUpload.tsx
- src/components/FormLabel/FormLabel.tsx
- src/components/Heading/Heading.tsx
- src/components/Icon/Icon.tsx
- src/components/InputValidationMessage/InputValidationMessage.tsx
- src/components/Modal/Modal.tsx
- src/components/Modal/components/ModalBody/ModalBody.tsx
- src/components/Modal/components/ModalFooter/ModalFooter.tsx
- src/components/Modal/components/ModalHeader/ModalHeader.tsx
- src/components/Pagination/Pagination.tsx
- src/components/RadioGroup/RadioGroup.tsx
- src/components/SelectInput/SelectInput.tsx
- src/components/Spinner/Spinner.tsx
- src/components/Table/Table.tsx
- src/components/Table/TableBody/TableBody.tsx
- src/components/Table/TableBody/TableBodyCell/TableBodyCell.tsx
- src/components/Table/TableHead/TableHead.tsx
- src/components/Table/common/TableRow/TableRow.tsx
- src/components/TextInput/TextInput.tsx
- src/components/TextLink/TextLink.tsx
- src/components/TextareaInput/TextareaInput.tsx
- src/components/TimePicker/TimePicker.tsx
- src/components/Toggle/Toggle.tsx
We might want to explore some better ways to make these interfaces available but for the time being this works and is helpful for library consumers extending our components since they can then extend the base props without having to re-write them.
> feat(types): export all prop interfaces

- src/components/DatePicker/DatePicker.stories.mdx
- src/components/TextInput/TextInput.module.scss
- src/components/TextInput/TextInput.stories.mdx
- src/components/TextInput/TextInput.stories.tsx
- src/components/TextInput/TextInput.test.tsx
- src/components/TextInput/TextInput.tsx
- src/styles/variables/forms.scss
Doc example: 
Created a separate "For Chromatic" stories file that has all permutations of sizes and prefix/suffix combinations for visual regression tests, without cluttering up the documentation.
> feat(TextInput): prefix and suffix option

- src/components/TextInput/TextInput.stories.mdx
- src/components/TextInput/TextInput.tsx
- src/styles/utilities.scss
- src/styles/white-space.scss
1.  white-space css utility classes
1.  fixes prefix/suffix wrapping. currently if a prefix or suffix value is multiple words, it can wrap depending on the TextInput container size, causing an input to look like:
after:
> prevent TextInput prefix/suffix from wrapping into multiple lines

- src/components/Button/Button.module.scss
- src/styles/variables/buttons.scss
Currently when hovering over an `isOutlined` button, it turns into a "solid" looking button. This code change updates the hover state appearance of `isOutlined` buttons so that it maintains an "outlined" appearance on hover.
Current:
https://user-images.githubusercontent.com/1447339/108289582-826f1e80-7143-11eb-9900-ad3b39e2d792.mov
Current in example:
https://user-images.githubusercontent.com/1447339/108289701-c4986000-7143-11eb-90f7-88c137ff38dc.mov
After:
https://user-images.githubusercontent.com/1447339/108289712-c95d1400-7143-11eb-905f-da62230dae46.mov
After in example
https://user-images.githubusercontent.com/1447339/108289766-e42f8880-7143-11eb-9680-e6bfd9839154.mov
> fix(Button): update hover state appearance of isOutlined Buttons

- src/components/Icon/Icon.test.tsx
- src/components/Icon/Icon.tsx
currently, Icon svgs are getting rendered with an empty `class` property instead of without one. 
This change prevents empty `class` property from being added to the svg.
> fix(Icon): prevent empty class property from being added to svg element

- src/components/DateInput/DateInput.Overview.stories.mdx
- src/components/DateInput/DateInput.tsx
- src/components/Popover/Popover.stories.mdx
- src/components/RadioGroup/RadioGroup.Overview.stories.mdx
- src/components/TextInput/TextInput.Overview.stories.mdx
- src/components/TextInput/TextInput.tsx
- src/components/TextInput/TextInputMasks.js
- src/components/TimePicker/TimePicker.Overview.stories.mdx
This PR addresses this issue:
https://github.com/palmetto/palmetto-components/issues/357
* we have made the dateinput readonly so that it does not trigger the mobile keyboard.
* we've added another default mask to allow for entering dates easily into a text input.
> fix(DateInput): Make date input read only.

- src/styles/overflow.scss
The responsive overflow classes weren't getting generated because we're using css vars when it's expecting scss.
> fix: overflow utility class breakpoints

- src/components/Pagination/Pagination.tsx
This PR addresses this issue: The Pagination component did not have keys on the list of PageButtons resulting in warnings
This adds the key prop to PageButton based on pageNumber
> add key to PageButton component

- src/components/Toggle/Toggle.module.scss
Prevents the toggle track from shrinking when width of the toggle's parent container is narrow. For example:
Should look like
> fix(Toggle): prevent toggle track from shrinking

- package.json
- src/components/SelectInput/SelectInput.tsx
- src/components/Spinner/Spinner.tsx
- src/docs/BorderRadius.stories.mdx
- src/docs/BorderWidth.stories.mdx
- src/docs/BoxShadow.stories.mdx
- src/docs/Breakpoints.stories.mdx
- src/docs/FontSize.stories.mdx
- src/docs/FontWeight.stories.mdx
- src/docs/Height.stories.mdx
- src/docs/LineHeight.stories.mdx
- src/docs/Spacing.stories.mdx
- src/docs/Width.stories.mdx
- src/docs/ZIndex.stories.mdx
- src/docs/colors/Colors.module.scss
- src/docs/colors/Colors.stories.jsx
- src/lib/tokens.ts
- webpack.config.js
- yarn.lock
This PR addresses this issue: https://trello.com/c/wQom9fAu/628-refactor-palmett-components-to-use-smaller-dictionary-formats
> perf(DictionarySize): refactor with smaller tokens dictionary format

- src/components/DateInput/DateInput.tsx
- src/components/Popover/Popover.Overview.stories.mdx
- src/components/Popover/Popover.VisualTests.stories.tsx
- src/components/Popover/Popover.test.tsx
- src/components/Popover/Popover.tsx
This PR addresses this issue: https://trello.com/c/bC292LqA
Palmetto.com has to force some clients to only render on the client-side instead of being server-side rendered. This fixes that for any components using Popover directly, but not through DateInput (DateInput forces withPortal to true, which renders it with a portalTarget of document.body).
LMK what you think of the typing, esp around the discriminated union. It prohibits setting portalTarget unless withPortal is true. I did this because we only ever need portalTarget if withPortal is true. I wanted to make it only required if withPortal is true but couldn't do that with the param initialization!
The typing for Popover isn't quite the same. Let me know if that's a problem.
the storybook …
> feat: allow popover to be server-side rendered

- src/styles/animation.scss
opacity values should be from `0` to `1`. For some reason the 100% value works in storybook, but the animation doesn't work (it just appears without fading) when used by another app.
https://developer.mozilla.org/en-US/docs/Web/CSS/opacity
> fix(animation): fix fade in animation

- src/styles/animation.scss
For tall modals (scrolling content) the 100% translateY causes some weird animation behavoir. This PR reduces the amount of Y position movement so that the modal doesn't have to travel as far.
Before (notice the jerkiness of the animation):
https://user-images.githubusercontent.com/1447339/119697329-ef5e1880-be04-11eb-9b79-cc0ae5deaead.mov
After:
https://user-images.githubusercontent.com/1447339/119697356-f4bb6300-be04-11eb-80c9-6159b5ebde62.mov
> fix: make fadeInUp animation more subtle for modals

- src/components/SelectInputNative/SelectInputNative.tsx
When selecting a utility provider and tariff, we receive the tarriffId as a number. When I pass in that number into the value field of the SelectInputNative, I get a type error that it doesn't match a string:
I believe SelectInputNative should accept a value that matches the types of the option's keys.
https://trello.com/c/74yuGx9I/1943-utility-rate-selection-limited-to-the-first-entry
Before Doc: 
After Doc:
> Updating value type to match available option types

- src/components/Button/Button.tsx
This PR just updates a few of the comments in the button component. I assumed these comments are being used to generate the prop description text seen in Storybook, which is where I noticed this issue:
So I came up with a description I thought would fit better for `isLoading`, basically copied from the example text above it in the docs. I also thought that mismatched string was more descriptive than the current `fullWidth` string, so I replaced that as well.
> Update prop descriptions for Button

- src/components/Formik/FormikSelectInputNative/FormikSelectInputNative.jsx
A js console error found when performing this fix: https://trello.com/c/74yuGx9I/1943-utility-rate-selection-limited-to-the-first-entry
Follows through on this issue that this PR did not fix: https://github.com/palmetto/palmetto-components/pull/497
I was able to copy the dist folder and copy it into my logistics-platform and confirm that this error is no longer present:
> Updating Formik Select Input to Match Select Input

- src/components/SelectInputNative/SelectInputNative.tsx
This PR addresses this issue: Option color in firefox is inherited from the select an as such, will have all options get the placeholder color which is too light.
> fix(SelectInputNative): option color inherited from select

- src/components/CheckboxInput/CheckboxInput.test.jsx
- src/components/CheckboxInput/CheckboxInput.tsx
- src/components/FormControl/FormControl.tsx
- src/components/FormLabel/FormLabel.Overview.stories.mdx
- src/components/FormLabel/FormLabel.Playground.stories.tsx
- src/components/FormLabel/FormLabel.module.scss
- src/components/FormLabel/FormLabel.test.jsx
- src/components/FormLabel/FormLabel.tsx
- src/components/Formik/FormikTextInput/FormikTextInput.test.jsx
- src/components/Formik/FormikTextareaInput/FormikTextareaInput.test.tsx
- src/components/RadioGroup/RadioGroup.module.scss
- src/components/RadioGroup/RadioGroup.tsx
- src/components/RadioGroup/RadioInput/RadioInput.tsx
- src/components/SelectInput/SelectInput.tsx
- src/components/TextInput/TextInput.test.tsx
- src/components/TextareaInput/TextareaInput.test.tsx
- src/components/TextareaInput/TextareaInput.tsx
- src/components/Toggle/Toggle.tsx
This PR addresses this issue: https://trello.com/c/kqgoPlHl/714-form-input-error-state-styling
For all form inputs, updates the "error" state so that the label remains dark grey instead of changing to red. 
Before
After PR
> Form label error styling

- src/lib/cssShorthandToClasses.ts
This PR addresses this issue: https://github.com/palmetto/palmetto-components/issues/528
> feat: [528] Add additional context to malformed css shorthand warning

- src/components/TextInput/TextInput.module.scss
This PR addresses this issue: [Text inputs are janky on iOS](https://trello.com/c/hXR5vDGD/1041-text-inputs-are-janky-on-ios)
This PR removes the background color from text inputs on focus to prevent this overflow behavior on mobile. Here is a screenshot of the issue:
> Remove background color from text input on focus

- src/components/Toggle/Toggle.VisualTests.stories.tsx
- src/components/Toggle/Toggle.constants.ts
- src/components/Toggle/Toggle.module.scss
- src/components/Toggle/Toggle.test.jsx
- src/components/Toggle/Toggle.tsx
Refactors the Toggle component so that FormLabel usage is independent of the actual toggle markup. This gives us more control and standardization of for helpText, error, and isRequired states. 
> refactor(Toggle): separate sub-component usage and add more visual tests

- src/components/FormLabel/FormLabel.test.jsx
- src/components/FormLabel/FormLabel.tsx
- src/components/Formik/FormikSelectInput/FormikSelectInput.test.jsx
- src/components/Formik/FormikSelectInputNative/FormikSelectInputNative.test.jsx
- src/components/Formik/FormikTextInput/FormikTextInput.test.jsx
- src/components/Formik/FormikTextareaInput/FormikTextareaInput.test.tsx
- src/components/Formik/FormikTimePicker/FormikTimePicker.test.tsx
- src/components/Formik/FormikTimePickerNative/FormikTimePickerNative.test.tsx
- src/components/SelectInput/SelectInput.test.jsx
- src/components/SelectInputNative/SelectInputNative.test.tsx
- src/components/TextInput/TextInput.test.tsx
- src/components/TextareaInput/TextareaInput.test.tsx
This PR addresses this issue: https://github.com/palmetto/helios-app/pull/231
On the app's login page, we wanted to require the Email and Password fields, but _not_ show the asterisk in the labels, as it's generally understood that all fields in a login form are required.
Wrapping the asterisk in a required field's label with a `span` and a class makes it a cinch to hide it with CSS, without requiring additional prop plumbing.
> Wrap required input label's asterisk in a targetable element

- src/components/TextLink/TextLink.module.scss
Allows css utility font size classes to get applied rather than always inheriting from the parent, for example:
`<TextLink className="font-size-sm font-size-md-tablet" />`
> fix(TextLink): allow font size utility classes to be applied

- src/components/Toggle/Toggle.test.jsx
- src/components/Toggle/Toggle.tsx
This PR addresses this issue: clicking the actual toggle switch doesn't change the check/unchecked state.
https://user-images.githubusercontent.com/1447339/127072184-92aa2ace-abb8-4ed1-9625-4d1a7a14f458.mov
> fix(Toggle): make toggle clickable

- src/components/TextareaInput/TextareaInput.module.scss
This PR addresses this issue: [Remove unnecessary background from TextareaInput when disabled](https://trello.com/c/fz1VjEzl/1101-remove-unnecessary-background-from-textareainput-when-disabled)
This PR adjusts the background color on disabled textarea inputs to prevent this UI issue in dark mode:
> Set background color to transparent when textarea is disabled

- src/components/SelectInputNative/SelectInputNative.module.scss
This PR addresses this issue: https://github.com/palmetto/palmetto-components/issues/527
For this case I just added extra padding on the right hand side. This prevents the text clashing with the caret, and maintains the native select interactivity for the entire element.
> fix(SelectInputNative): adding extra padding to prevent arrow overlap

- src/components/Details/DetailsSummary.tsx
This PR addresses this issue: https://github.com/palmetto/palmetto-components/issues/541
The issue is present because we prevent default on the keyDown even in the summary element. This is done because if we don't, then the details will expand on their own (part of HTML spec) and we will have mismatching state, which means we no longer have a controlled component. The solution is to only prevent default on the event when the user is actually expanding with the ENTER or SPACE keys. All other keydown events will proceed as usual, which fixes tabbing.
> fix(Details): only prevent default when toggling open panel

- src/components/Button/Button.test.jsx
- src/components/Button/Button.tsx
For Button, a target attribute wasn't being added to the button tag when one was passed as a prop; this prevented being able to use `target="_blank"`, for example. This PR fixes this, and adds a test to validate the change.
> Add target attribute if one is passed as a prop

- src/components/TextInput/TextInput.module.scss
This PR addresses this issue: https://palmetto.zendesk.com/agent/tickets/318709
We never caught this b/c chromatic doesn't run on safari at the moment.
safari:
chrome:
> fix: disabled text input text color

- src/components/DateInput/DateInput.test.tsx
- src/components/DateInput/DateInput.tsx
This PR addresses this issue: https://github.com/palmetto/palmetto-components/issues/496
`DateInput` component is now set to close the popover upon date selection by the user, EXCEPT in cases where `selectsRange` is true, since the user is expected to select multiple dates before exiting the popover.
> fix(DateInput): Date picker close on selection

- src/components/Modal/Modal.module.scss
This PR addresses this issue: https://trello.com/c/8MT98ssJ/719-consumers-of-palmetto-components-are-seeing-a-console-warning-to-include-the-reach-dialog-styles
Currently, users are getting a warning for not including @reach/dialog styles, while it is only present in DEV/test environments, it is confusing nonetheless. We don't use these styles so we don't want to import them, but B=by setting --reach-dialog CSS variable to `1`, it lets the library know that styles are present (we are tricking it basically).
> fix(Modal): add flag to avoid reach CSS warning

- src/components/TextareaInput/TextareaInput.Overview.stories.mdx
- src/components/TextareaInput/TextareaInput.VisualTests.stories.tsx
- src/components/TextareaInput/TextareaInput.module.scss
- src/components/TextareaInput/TextareaInput.tsx
- src/components/TextareaInput/TextareaInputSizeUtilities.test.ts
- src/components/TextareaInput/TextareaInputSizeUtilities.ts
This PR addresses this issue: https://github.com/palmetto/palmetto-components/issues/437
Added size + responsive utilities to `TextareaInput` component. 
> add size + responsive size to TextareaInput

- package.json
- src/components/TabsSlider/TabsSlider.Playground.stories.tsx
- src/components/TabsSlider/TabsSlider.test.tsx
- src/components/TabsSlider/TabsSlider.tsx
- yarn.lock
This PR addresses this issue: https://github.com/palmetto/palmetto-components/issues/566
While the original implementation worked in almost every case, we did run into some cases like noted in the issue above, where the initial rendering of the selected tab indicator would have the wrong width. Currently the width is updated when any of a number of things happen, such as:
* window size changes.
* active tab changes
* children prop in the component changes.
it seems that this wasn't enough to cover situations in which width changes are triggered by unforeseen cascading of rendering changes when the component interacts with a complex page. 
The solution was to rely on the `ResizeObserver` api to track resizing specific to our component's room DOM node, as opposed to only the window resizing …
> fix(TabsSlider): move to element resize observer

- src/docs/FontFamily.stories.mdx
- src/styles/variables/tokens.scss
We're currently not making the font family design tokens available as css variables. This PR fixes that as well as corrects the variable names in the documenation. 
> fix: export font-family css var design tokens and correct documentation

- src/lib/createComponent/createComponent.Overview.stories.mdx
Corrects the border width prop name from `border` to `borderWidth`
> docs(createComponent): correct border width prop name

- src/components/Modal/Modal.module.scss
This PR addresses this issue: https://github.com/palmetto/palmetto-components/issues/672
Before: 
After:
- The changes are only relevant in app
- I added a screenshot to this PR showing the change using XCode Simulator
> fix(modal): prevent full screen modal from overflowing beyond safe viewport area

- src/components/Modal/Modal.VisualTests.stories.jsx
- src/docs/constants.ts
- yarn.lock
Updates chromatic visual regression tests to use 350px instead of 320px since most modern phones are greater than 350px width.
> test: update phone breakpoint to 350px

- src/components/Alert/Alert.Overview.stories.mdx
- src/components/Heading/Heading.Overview.stories.mdx
- src/components/Heading/Heading.module.scss
- src/components/Heading/Heading.tsx
- src/styles/variables/headings.scss
- src/styles/variables/index.scss
- yarn.lock
Allows font-family, font-weight, and line-height to be themed for the Heading component
This PR addresses this issue: https://trello.com/c/0BYfsU0F/1147-update-components-for-themability
> feat(Heading): document and enable theming

- src/components/Button/Button.Playground.stories.tsx
- src/components/Button/Button.VisualTests.stories.tsx
- src/components/Button/Button.tsx
This PR addresses this issue:  #732
This PR gives the Button component a more strict type signature to prevent accidental adding of react props to DOM elements. While this wouldn't adversely affect the dotcom team, I'm not familiar with how other teams are using this library so let me know if this would be too much trouble for other users.
I've kept the old `ButtonProps` type signature for backward compatibility in the case where others were using this type for their own components. If it would be preferred to make this a breaking change just to only have one set of props let me know.
> Fix: [732] Implement Stricter ButtonProps

- src/components/Card/Card.Overview.stories.mdx
- src/components/Card/Card.module.scss
- src/components/Card/Card.tsx
- src/components/Card/components/CardFooter/CardFooter.tsx
- src/components/Card/components/CardHeader/CardHeader.tsx
- src/components/Card/components/CardSection/CardSection.test.jsx
- src/components/Card/components/CardSection/CardSection.tsx
This PR addresses this issue: https://trello.com/c/AeUi6Yvb/1209-card-if-a-box-prop-is-used-do-not-apply-the-card-classes
With the recent implementation of component design tokens to enable theming, currently there is no way to allow for single-instance (or one-off) styling of a Card and it's child components. This is due to the fact that the classes applied by the Card.module.scss will always have a higher level of specificity than the utility classes that get applied via BoxProps.
This pr makes it so that using any BoxProp whose css attribute matches the Card's will take precendent over the component design token's css attribute. This allows users of the component to use the default styles, use customize the appearance of their cards using the component design tokens, or have one-off …
> feat(Card): enable one-off styling through BoxProps while maintaining theming

- src/components/Button/Button.test.jsx
- src/components/Button/Button.tsx
This PR addresses this issue: Currently there is a conflict between the custom `type` prop in `BaseButtonProps` and the actual `type` attribute that comes from `ButtonHTMLAttributes`. Here I have removed the custom type prop so we only have the intrinsic attribute remaining.
> fix(Button): remove custom button type

- src/components/Button/Button.tsx
This PR addresses this issue: With the removal of the type prop in the button, we had no proper default in place. This adds the type default once more which is semantically correct.
> fix(Button): default to button type if attribute not passed and is actual button

- src/components/MediaModal/MediaModal.Overview.stories.mdx
- src/components/MediaModal/MediaModal.Playground.stories.tsx
- src/components/MediaModal/MediaModal.VisualTests.stories.tsx
- src/components/MediaModal/MediaModal.module.scss
- src/components/MediaModal/MediaModal.test.tsx
- src/components/MediaModal/MediaModal.tsx
without requiring title, description or headerContent
This PR addresses this issue: #748 
Allows users to render a close button in the upper right of the viewport without defining `title`, `description`, or `headerContent` props.
> feat(MediaModal): add closeButton prop to render a visible close button

- src/components/TimePicker/TimePicker.Codesandbox.stories.mdx
Fixes console warning from storybook about importing directly from '@storybook/addon-docs/blocks'.
> fix: storybook import add-ons/blocks console warning

- src/components/Modal/Modal.Overview.stories.mdx
- src/components/Modal/Modal.module.scss
This PR addresses this issue: #727 
Adds deliberate styles to the focus state of a Modal's close button
> fix(Modal): style focus state for close button

- src/components/Badge/Badge.tsx
There are cases where we want to pass a node (e.g. `<Duration />`) as the message in a Badge. This changes would allow that without generating typescript errors.
Alternatively, we could add a `children` prop to Badge and leave `message` as is. 
> fix(Badge): allow message prop to accept nodes in addition to strings

- .github/workflows/semantic-release.yml
This PR addresses this issue: Release action can no longer push to the repo.
> fix: add explicity permission keys for release action

- src/components/Button/Button.test.jsx
- src/components/Button/Button.tsx
This PR addresses this issue: #769 
Stops this console warning from appearing while running locally. 
> fix(Button): html type property getting set to boolean value

- src/components/OptionTile/OptionTile.VisualTests.stories.tsx
- src/components/OptionTile/OptionTile.module.scss
- src/components/SelectInput/SelectInput.module.scss
- src/components/SelectInputNative/SelectInputNative.module.scss
- src/components/TextareaInput/TextareaInput.module.scss
Adds visible focus states to OptionTile, SelectInput, SelectInputNative and TextareaInput components. Also adds chromatic snapshots if they didn't already exist to cover focus states.
> fix: OptionTile, SelectInput, SelectInputNative, TextareaInput focus states

- src/components/Table/Table.Overview.stories.mdx
- src/components/Table/common/TableRow/TableRow.test.tsx
- src/components/Table/common/TableRow/TableRow.tsx
- src/types/index.ts
Allow cellClassName to be a function and pass the same data as render so that consumers can use that data to choose a class.
- [ x My code has no linting or typescript compile warnings.
> feat: add support for table cell class names to be generated via a function

- src/components/Table/Table.Overview.stories.mdx
- src/components/Table/Table.module.scss
- src/components/Table/TableBody/TableBodyCell/TableBodyCell.module.scss
- src/components/Table/TableHead/TableHeaderCell/TableHeaderCell.module.scss
This PR addresses this issue: https://palmetto-team.slack.com/archives/C014E879QCX/p1655163348578379
Moves the background color specificity to the `Table` rather then to each `cell`. This allows consumers to customize the styling of table rows and cells via other means.
> fix(Table): apply bg color to Table rather then cells

- .github/workflows/semantic-release.yml
Publish to [GitHub Packages](https://github.com/features/packages) in addition to NPM, so that we can publish private packages in GitHub Packages and use them alongside palmetto-components.
Context: 
- https://github.community/t/github-package-registry-with-private-packages-proxying-scope-to-npm/2782
- https://sevic.dev/npm-publish-github-actions/
> chore: publish to GitHub Packages

- .github/workflows/semantic-release.yml
Publishing to GitHub Packages (along with https://github.com/palmetto/palmetto-design-tokens/pull/208) using `yarn publish` instead of calling `semantic release` twice.
> build: publish to github packages

- src/components/Drawer/Drawer.VisualTests.stories.tsx
- src/components/Drawer/Drawer.module.scss
Currently, if the content of a Drawer is taller than the viewport height on Drawers with placement set to `top` or `bottom`, the Drawer height grows, which has the side effect of not allowing the drawer content to scroll. 
This sets a max-height for top and bottom placed Drawers so that it's contents will be scrollable.
> fix(Drawer): prevent top/bottom placement drawers from being taller then viewport

- src/components/Card/Card.Overview.stories.mdx
- src/components/OptionTile/OptionTile.Overview.stories.mdx
- src/components/OptionTile/OptionTile.module.scss
This PR addresses this issue: https://github.com/palmetto/palmetto-components/issues/800
Use the form-control line-height token.
> fix(OptionTile): prevent line-height from being accidentally overridden by parent

- src/components/OptionTileGroup/OptionTileGroup.Overview.stories.mdx
- src/components/OptionTileGroup/OptionTileGroup.tsx
Now, only the "Loanpal 20 Year 3.99%" appears as if it has an error
> Allow OptionTileGroup options to have individual errors

- src/components/Toggle/Toggle.Overview.stories.mdx
- src/components/Toggle/Toggle.module.scss
Adds a visual error state for Toggles that's checked on. 
> feat (Toggle): error state for Toggles that are on

- src/components/RadioGroup/RadioInput/RadioInput.tsx
Prevents ancestors from pushing the "hidden" radio input down by ensuring it's relative to it's parent.
> fix(RadioInput): prevent ancestors from impacting radio button position

- src/components/Tabs/Tabs.Overview.stories.mdx
- src/components/Tabs/Tabs.tsx
This PR addresses this issue: #805 
Counting react children: https://www.agney.dev/blog/react-children-count
> fix(Tabs): correct aria-setsize count when Tabs are conditionally rendered

- src/components/TextInputFloating/TextInputFloating.Overview.stories.mdx
- src/components/TextInputFloating/TextInputFloating.Playground.stories.tsx
- src/components/TextInputFloating/TextInputFloating.VisualTest.stories.tsx
- src/components/TextInputFloating/TextInputFloating.module.scss
- src/components/TextInputFloating/TextInputFloating.test.tsx
- src/components/TextInputFloating/TextInputFloating.tsx
- src/components/index.ts
- src/docs/FormTheming.stories.mdx
- src/stories/FormControls.stories.mdx
Adds the TextInputFloating component. 
https://palmetto.atlassian.net/browse/UX-621
Documentation: https://5ed9214b642dc10022b50a2d-adfobghjbr.chromatic.com/?path=/docs/components-textinputfloating-overview--default-story
> feat(TextInputFloating): new floating label text input component 

- src/components/SelectInput/SelectInput.module.scss
Updates styles for multiselect component for light and dark mode.
> fix: update styling for light and dark mode

- CHANGELOG.md
- src/components/Table/Table.tsx
- src/components/Table/TableBody/TableBody.tsx
- src/hooks/useExpandableRow/useExpandableRow.test.tsx
- src/hooks/useExpandableRow/useExpandableRow.ts
Types for `expandedRow` (`Key | undefined`) and `onExpandedRowChange` (`Dispatch<SetStateAction<Key | null>>`) did not match, causing one or the other to always have a type error:
> Make Table expandedRow and onExpandedRowChange types consistent
